### ISSUE TITLE
that._buildBody is not a function

### ISSUE THREAD

**Issue by shellprog** [metajack/strophejs-plugins#109]
Unable to get strophe.register.js working . I have added strophe.js before loading this plugin

```
<script type='text/javascript' src="/js/strophe.min.js"></script>
<script type="text/javascript" src="/js/strophe.register.js"></script>
<script type='text/javascript' src='/js/echobot.js'></script>
```

and in default example echobot added 

```
var callback = function(status) {
                if (status === Strophe.Status.REGISTER) {
                    connection.register.fields.username = "juliet";
                    connection.register.fields.password = "R0m30";
                    connection.register.submit();
                } else if (status === Strophe.Status.REGISTERED) {
                    console.log("registered!");
                    connection.authenticate();
                } else if (status === Strophe.Status.CONNECTED) {
                    console.log("logged in!");
                } else {
                    // every other status a connection.connect would receive
                }
            };
            connection.register.connect("example.com", callback);
```

After getting valid connection object but it seems strophe.register is unable to access any method from strophe library . Please help .

**Comment by emanuelef** [comment]
Same issue, have you found a way to make it work ?
In my case I connect using websockets.
Thanks a lot

**Comment by shellprog** [comment]
not yet found i am using openfire web services with security at present .

**Comment by mcnesium** [comment]
are there any news here?

**Comment by fasholaide** [comment]
I had same issues. It's best you use this plugin: https://github.com/strophe/strophejs-plugins/tree/master/register instead. I hope it helps...

**Comment by avijit-brainium** [comment]
@fasholaide the given link is not available, please let me know where can I get the working one.

**Comment by subkhansarif** [comment]
Any updates? I have the same issue.

**Comment by dexter21r** [comment]
Use this plugin instead. https://raw.githubusercontent.com/strophe/strophejs-plugin-register/master/strophe.register.js

**Comment by tanglinhai** [comment]
Neither of the above links can be used. Use my branch to fix the problem of unable to register and authenticate (support the latest version of strophe1.2.16. JS)
https://github.com/tanglinhai/strophejs-plugins.git
