### ISSUE TITLE
MUC plugin modifyUser query uses wrong namespace

### ISSUE THREAD

**Issue by jbermudes** [metajack/strophejs-plugins#31]
the function modifyUser uses the namespace NS_OWNER instead of the NS_ADMIN namespace. This appears to be against the XMPP MUC specification. I do not know if this is an error or a workaround for a particular server, but I thought I'd post here in case anyone else is trying to figure out why kicking and banning doesn't work.

**Comment by Gordin** [comment]
You're right, the XEP only uses the owner namespace to manipulate the room itself, not the users, I submitted a fix
