### ISSUE TITLE
PubSub plugin: getNodeSubscriptions uses wrong NS

### ISSUE THREAD

**Issue by patters** [metajack/strophejs-plugins#48]
The getNodeSubscriptions method in strophe.pubsub.js uses the pubsub#owner namespace. It should use the unadorned Strophe.NS.PUBSUB namespace.

**Comment by astro** [comment]
I disagree. `<subscriptions xmlns='http://jabber.org/protocol/pubsub'/>` doesn't accept a `node` attribute. It would be used in a function like `getMySubscriptions()` or `getUserSubscriptions()`. Compare XEP-0060's [5.6 Retrieve Subscriptions](http://xmpp.org/extensions/xep-0060.html#entity-subscriptions) vs [8.8.1 Retrieve Subscriptions List](http://xmpp.org/extensions/xep-0060.html#owner-subscriptions-retrieve).

**Comment by patters** [comment]
Example 24 in the XEP under section 5.6 shows a subscriber querying for their subscriptions to a particular node (presumably to retrieve different subscription id's to the same node).

I was reading this API as "get MY subscriptions to a particular node" and not the owner use case of "get the subscribers to MY node". I'd therefore suggest that the plugin have two API's:
1. getNodeSubscribers() -- renaming the current API to this
2. getNodeSubscriptions() -- cloning the current API and removing the owner NS

Perhaps better yet would be to decorate the API names with "owner" or
"subscriber"..
