### ISSUE TITLE
Remove/Rename strophe.caps.js or strophe.CAPS.js

### ISSUE THREAD

**Issue by mweibel** [metajack/strophejs-plugins#78]
hi,

it causes git to be confused when both have the same name. Don't know if this is a git bug but I can't add the file (don't know why I do have to add the file but it doesn't seem to work):

``` bash
michael@michael libs/strophejs-plugins (master *) » git st
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   caps/strophe.CAPS.js
#
no changes added to commit (use "git add" and/or "git commit -a")
michael@michael libs/strophejs-plugins (master *) » git add caps/strophe.CAPS.js 
michael@michael libs/strophejs-plugins (master *) » git st
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   caps/strophe.CAPS.js
#
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by flosse** [comment]
Which version of git do you use? I never had an issue like this. My current git version is 1.7.9.5

**Comment by mweibel** [comment]
hmm strange :S Which platform do you run on?
I'm on a Mac and git version is 1.7.10 (atm, don't know if I had a different version as I posted the issue, I'll need to take a look again).

**Comment by flosse** [comment]
I'm working on Ubuntu 12.04.

**Comment by mweibel** [comment]
I encountered this problem again using mac and git version 1.7.10.4.. this is annoying ;) (Not only for a users point of view).
We should rename one.

//Edit: I know why: Mac OSX by default has a case insensitive filesystem (damn!) and therefore it can't distinguish between those two files. I set now my git config to `core.ignorecase = false` and hope it works..

**Comment by mweibel** [comment]
Doesn't work. So @flosse I'd recommend renaming one of the files to something different..

**Comment by flosse** [comment]
ok, feel free to rename or delete one of them!
